query menuQuery($name: String!) 
{
  menuByName(name: $name) {
    # name
    # description
    links {
      # expanded
      description
      # attribute
      label
      url {
        # routed
        path
      }
    }
  }
}