query pageQuery($path: String!) 
{
  route(path: $path) {
    # routed
    path
    ... on EntityCanonicalUrl {
      nodeContext {
        # entityLabel
        ... on NodePage {
          title
          nid
        	uuid
        	vid
          # entityUuid
          # entityId
          entityBundle
          entityType
          entityPublished
          nid
          uuid
          vid
          # revisionTimestamp
          # revisionLog
          status
          created
          entityCreated
          changed
          entityChanged
          promote
          sticky
          # defaultLangcode
          # revisionDefault
          # revisionTranslationAffected
          # entityRendered
          body {
            format
            value
          }
        }
      }
    }
  }
}

# {
#   nodeById(id: "1") {
#     entityLabel
    # ... on NodePage {
    #   title
    #   body {
    #     value
    #     format
    #   }
#     }  
#   }
# }